name: Fix Playwright versions

on:
  push:
    branches:
      - 'dependabot/npm_and_yarn/playwright/test-*'

permissions:
  contents: read

jobs:
  fix-playwright-versions:
    name: 'Fix Playwright versions'
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v6.0.0
        with:
          token: ${{ secrets.PREREVIEW_BOT_TOKEN }}

      - name: 'Set up Node.js'
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: package.json
          cache: ${{ !env.ACT && 'npm' || '' }}

      - name: 'Install dependencies'
        run: npm ci --engine-strict --ignore-scripts

      - name: 'Fix Playwright versions'
        run: scripts/fix-playwright-versions.sh

      - name: 'Commit changes'
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        if: ${{ !env.ACT }}
        with:
          commit_message: '[dependabot skip] Fix Playwright versions'
          commit_user_name: 'prereview-bot'
          commit_user_email: 'engineering@prereview.org'
          commit_author: 'prereview-bot <engineering@prereview.org>'
